# Generated by Django 5.2.4 on 2026-01-31 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStorefront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storefront_name', models.CharField(default='My Crowdfund Store', max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('about_text', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='storefronts/logos/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='storefronts/banners/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='storefronts/favicons/')),
                ('template', models.CharField(choices=[('modern', 'Modern & Clean'), ('bold', 'Bold & Colorful'), ('minimal', 'Minimal & Professional'), ('creative', 'Creative & Artistic')], default='modern', max_length=20)),
                ('primary_color', models.CharField(default='#3498db', max_length=7)),
                ('secondary_color', models.CharField(default='#2c3e50', max_length=7)),
                ('accent_color', models.CharField(default='#27ae60', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#333333', max_length=7)),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS code')),
                ('custom_html_header', models.TextField(blank=True, help_text='Custom HTML for header section')),
                ('custom_html_footer', models.TextField(blank=True, help_text='Custom HTML for footer section')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('show_featured_projects', models.BooleanField(default=True)),
                ('projects_per_page', models.IntegerField(default=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storefront', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StorefrontSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Banner'), ('about', 'About Section'), ('projects', 'Projects Grid'), ('stats', 'Statistics'), ('testimonials', 'Testimonials'), ('contact', 'Contact Form'), ('custom', 'Custom HTML')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='accounts.userstorefront')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
